// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { PrismaPg } from '@prisma/adapter-pg';

export default defineConfig({
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // url: process.env.DATABASE_URL as string,

    url: 'postgresql://music_room_user:oEhb7utCFpaspJVzIT9FrZgPbTAp65e2rV6P8uW2v7l2OeXmuDV2G14UQSgJgchd@db:5432/music_room_db?schema=public',
  },
  // schema: 'prisma/schema.prisma',
});
